root='/dss/dsshome1/07/lu64bag3/src/cpmd/uspp_xc/CPMD.ORG/'
arch='../build/sng'
version='x'
nproc=
bin='${root}/${arch}/bin/cpmd.${version}'
testsrc='${root}/regtests/tests'
ppdir='${root}/regtests/tests/PP_LIBRARY/'
make='make -j${nproc}'
makedir='${root}/${arch}/'
#cvs_update='cvs update -dP'
nproc_mpi=2
mpi_prefix='mpirun -n %i'
mpi_suffix='-hostfile localhost'
mpi_suffix=''
