C hello emacs, this is -*- fortran -*-
      SUBROUTINE GLS(IUNIT,PRGSTR)
C args
      INTEGER IUNIT
      CHARACTER PRGSTR*(*)
C includes
      INCLUDE 'md.h'
      INCLUDE 'formats.h'
C local vars
      CHARACTER STR*(55)
CCC      CHARACTER VSTR*(6)
C data
      DATA STR /'NLATSM,KXMAX,KYMAX,KZMAX,K2MAX,ALPHA,PBETA,NGHTUP'/
C begin
      CALL GIMME(IUNIT,PRGSTR,STR)
      CALL CHPINT(NLATSM,PRGSTR,STR)
      CALL CHPINT(KXMAX,PRGSTR,STR)
      CALL CHPINT(KYMAX,PRGSTR,STR)
      CALL CHPINT(KZMAX,PRGSTR,STR)
      CALL CHPINT(K2MAX,PRGSTR,STR)
      CALL CHPREL(ALPHA,PRGSTR,STR)
      CALL CHPREL(PBETA,PRGSTR,STR)
      CALL CHPINT(NGHTUP,PRGSTR,STR)
      CALL CHKMTY(PRGSTR,STR)
      CALL GTEND(IUNIT,PRGSTR)
C end GLS
      END

      SUBROUTINE PLS
C includes
      INCLUDE 'md.h'
      INCLUDE 'mdblock.h'
C begin
      IF (LGOT(NLATSB)) THEN
        PRINT *,BTNAME(NLATSB)
        PRINT '(8A10)','NLATSM','KXMAX','KYMAX','KZMAX',
     $       'K2MAX','ALPHA','PBETA','NGHTUP'
        PRINT '(5I10,2F10.3,I10)',NLATSM,KXMAX,KYMAX,KZMAX,
     $       K2MAX,ALPHA,PBETA,NGHTUP
        IF (NLATSM .EQ.NCTOFF) THEN
          PRINT 500
        ELSEIF (NLATSM.EQ.NEWALD) THEN
          PRINT 510
        ELSE
          PRINT 520
        ENDIF
      ELSE
        PRINT 500
      ENDIF
      PRINT *
 500  FORMAT (4X,' CUTOFF TRUNCATION/REACTION FIELD WILL BE USED')
 510  FORMAT (4X,' THE EWALD SUM METHOD WILL BE USED')
 520  FORMAT (4X,' THE PPPM METHOD WILL BE USED')
C end pls
      END
