C hello emacs, this is -*- fortran -*-
c
C  Save system status for qmmm
c
      common/c1i/NRPT3,NSOLV3,NATTO3,I3,K,N,NITP,NITS,NCONP,NCONBC,
     c           II,NDOF,NBATH,NBNUM,NBNDX,IFSTEP,NLIM,NSPG
 
      common/c1l/LMONO,LOCTO,LVAC,LDOVIR,LDOPER,LPR4,LDOPIN,LDODLA,
     c           LDOVDL,LDODMU,LDOVDM,LWR4,LREMCM,LPRLSQ,LSHKPR,
     c           LSHKSO,LERR,LEVERY,LFORM,LSEWRT,LSECPY
 
      common/cr1/TOTMAS,TMASS,SUBMAS,SUBMIN,DTHALF,BOHALF,XCM,VCM,
     c           ACM,OCM,EKCM,EKCMTO,EKROT,XMIN,
     c           TMP,EDUM,TFACPR,SCAL,ESCL,
     c           EKNOW,TEMP,TMPAVE,TMPFLC,EKREF,EKBATH,SCLBAT,DTBATH,
     c           TFACBT,EKTMP,SCLTMP,EKIN4B,EKIN40,CW4D,VELCM,DTCP,
     c           FITAR,VIR,PRES,VIRTOT,PRESTO,EPLJ,EPLJAV,EPLJFL,EPEL,
     c           EPELAV,EPELFL,EPRF,EPRFAV,EPRFFL,EPRC,EPRCAV,EPRCFL,
     c           ENER,EPAVE,EPFLC,DEDLAM,DEDLAV,DEDLFL,DEDMU,DEDMAV,
     c           DEDMFL,DVDL,DVDM,ENERES,EREAVE,EREFLC,VOLPRT,VPAVE,
     c           VPFLC,DLAM,DMU
 
      common/crr1/DTMP,TMPSUM,TMPSQ,
     c           EPLJSU,EPLJSQ,EPELSU,EPELSQ,EPRFSU,EPRFSQ,EPRCSU,
     c           EPRCSQ,EPSUM,EPSQ,DEDLSU,DEDLSQ,DEDMSU,DEDMSQ,
     c           ERESUM,ERESQ,VPSUM,VPSQ                          
c
C  Save system status for qmmm
c
!      common/c1i/NRPT3,NSOLV3,NATTO3,I3,K,N,NITP,NITS,NCONP,NCONBC,
!     c           II,NDOF,NBATH,NBNUM,NBNDX,IFSTEP,NLIM,NSPG
!!
!      common/c1l/LMONO,LOCTO,LVAC,LDOVIR,LDOPER,LPR4,LDOPIN,LDODLA
!      common/c2l/LDOVDL,LDODMU,LDOVDM,LWR4,LREMCM,LPRLSQ,LSHKPR
!      common/c3l/LSHKSO,LERR,LEVERY,LFORM,LSEWRT,LSECPY

!      common/cr1/TOTMAS,TMASS,SUBMAS,SUBMIN,DTHALF,BOHALF,XCM,VCM
!      common/cr2/ACM,OCM,EKCM,EKCMTO,EKROT,XMIN,
!     c          TMP,EDUM,TFACPR,SCAL,ESCL
!      common/cr3/EKNOW,TEMP,TMPAVE,TMPFLC,EKREF,EKBATH,SCLBAT,DTBATH
!      common/cr4/TFACBT,EKTMP,SCLTMP,EKIN4B,EKIN40,CW4D,VELCM,DTCP
!      common/cr5/FITAR,VIR,PRES,VIRTOT,PRESTO,EPLJ,EPLJAV,EPLJFL,EPEL
!      common/cr6/EPELAV,EPELFL,EPRF,EPRFAV,EPRFFL,EPRC,EPRCAV,EPRCFL
!      common/cr7/ENER,EPAVE,EPFLC,DEDLAM,DEDLAV,DEDLFL,DEDMU,DEDMAV
!      common/cr8/DEDMFL,DVDL,DVDM,ENERES,EREAVE,EREFLC,VOLPRT,VPAVE
!      common/cr9/VPFLC,DLAM,DMU
!
!      common/crr1/DTMP,TMPSUM,TMPSQ
!      common/crr2/EPLJSU,EPLJSQ,EPELSU,EPELSQ,EPRFSU,EPRFSQ,EPRCSU
!      common/crr3/EPRCSQ,EPSUM,EPSQ,DEDLSU,DEDLSQ,DEDMSU,DEDMSQ
!!!!!      common/crr4/ERESUM,ERESQ,VPSUM,VPSQ
